export type GuideTopic = {
  id: string;
  title: string;
  simple: string;
  why: string;
  inputs: string;
  outputs: string;
  example: string;
  connections: string[];
  action: string;
  limitations: string;
  technical: string;
};
function topic(
  id: string,
  title: string,
  simple: string,
  why: string,
  inputs: string,
  outputs: string,
  example: string,
  connections: string[],
  action: string,
  limitations: string,
  technical: string,
): GuideTopic {
  return {
    id,
    title,
    simple,
    why,
    inputs,
    outputs,
    example,
    connections,
    action,
    limitations,
    technical,
  };
}
export const guideTopics: GuideTopic[] = [
  topic(
    "start",
    "ProjectTrace in 60 Seconds",
    "ProjectTrace checks your software and its technical statements, shows what the evidence supports, and helps your team act on problems.",
    "People make better decisions when engineering information stays connected to proof.",
    "Authorized source ZIPs, documentation, configuration and supported dependency manifests.",
    "Claims, evidence, findings, change history and explainable review decisions.",
    "A README says JWT. The latest code configures sessions. ProjectTrace shows the contradiction and its exact source.",
    ["how-it-works", "product-map", "workflows"],
    "Explore the synthetic demo, then import a repository into your own workspace.",
    "Static observations do not prove how an application behaves in production.",
    "Deterministic analyzers create snapshot-scoped observations; the Claim Ledger and Evidence Graph connect them to verification, impact, policies and human review.",
  ),
  topic(
    "how-it-works",
    "How ProjectTrace Works",
    "Upload source, inspect the analysis, follow the proof, and decide what needs attention.",
    "A conclusion is useful when you can trace it back to its source and scope.",
    "Files from a bounded safe ZIP or an authorized source connection.",
    "Versioned evidence, atomic claims, native findings and a review queue.",
    "Upload → analysis → evidence → claim verification → review and audit.",
    ["repositories", "evidence", "claims", "reviews"],
    "Check analysis coverage before interpreting a result.",
    "Unsupported files and failed engines make coverage partial; no finding does not automatically mean safe.",
    "Content hashes and analyzer versions drive cached observation reuse. Graph records and snapshots are committed atomically. Queued execution uses encrypted, expiring inputs.",
  ),
  topic(
    "product-map",
    "Product Map",
    "Every module follows one chain: source, evidence, what is true, what changed, and what a person should do.",
    "Quality, security and cloud observations are more useful when they share context.",
    "Source, docs, dependency and infrastructure observations; authorized cloud inventory where connected.",
    "Connected claims, findings, impact, review decisions and audit events.",
    "Click a stage in the map below to learn how it connects to the next one.",
    ["evidence-graph", "claims", "drift", "pull-requests", "audit"],
    "Start with a claim or finding and follow its evidence rather than browsing an entire graph.",
    "Relationships require evidence; similar names never prove a deployment mapping.",
    "PostgreSQL relational records represent snapshot-scoped nodes and typed edges. Graph neighborhoods are bounded and authorization-filtered.",
  ),
  topic(
    "repositories",
    "Repository Analysis",
    "A repository is a source collection. A snapshot records the version that ProjectTrace actually analyzed.",
    "You need a stable reference when discussing a finding or change.",
    "Source ZIP, supported files, optional branch/commit metadata.",
    "An analysis job, source artifacts, coverage and a new snapshot.",
    "Use New repository for a different project; Upload new snapshot for the next version of the same project.",
    ["scope", "how-it-works", "drift"],
    "Open Repositories, import your ZIP, then check the real job state and engine coverage.",
    "Imported builds, tests, scripts and package installers are never run. Local ZIPs may lack a verified SCM commit.",
    "Safe extraction enforces traversal, symlink, count and byte budgets. Snapshot identity, hashes and analyzer versions distinguish source changes from analyzer upgrades.",
  ),
  topic(
    "code-quality",
    "Code Quality",
    "Code Intelligence shows supported reliability problems and code that may be harder to maintain. Every observation links to its rule, symbol and snapshot evidence.",
    "Review new problems first, while retaining a visible baseline and the history of existing issues.",
    "Bounded Python AST, JavaScript/JSX, TypeScript/TSX and Java syntax; organization/repository profiles; an explicitly selected BASE and HEAD; optional LCOV or coverage XML reports.",
    "Separate reliability/maintainability findings, measurable complexity and size, native duplicate blocks, coverage provenance, maintenance hotspots, snapshot trends and an explainable quality gate.",
    "A mutable Python default appears as a reliability observation. Moving the function down 20 lines keeps its symbol identity. Removing it resolves the machine observation; bringing it back in the BASE ancestry reopens it.",
    ["findings", "pull-requests", "policies", "evidence-graph"],
    "Choose repository and HEAD in Code Quality. Select an accepted BASE in Rules & Profiles before analyzing a new HEAD. Inspect New Code, measured contributors and duplicate occurrences; import the report produced for that exact source revision in Coverage. Record review decisions with a reason.",
    "All supported languages have PARTIAL maturity: syntax rules are bounded, not complete control-flow/type/framework analysis. Missing coverage is Not available, never zero. Reports do not prove their own producer execution. Hotspot changes use observed snapshots, not invented Git history. Renames create new quality identities.",
    "Cyclomatic = 1 + recorded decisions/boolean alternatives. ProjectTrace cognitive = sum(decision contribution * (1 + enclosing syntax-control depth)), with direct same-name recursion in Python. Tokens normalize comments and local bindings, retain operators and literal hashes, and require 50 tokens/6 lines by default. Quality fingerprints use rule + path + qualified symbol + symptom anchor, not line. New Code gates use explicit BASE ancestry; stable rules can fail, beta rules request review, and unavailable baseline/coverage yields Review required. Quality results feed the unified advisory engineering/PR gate. Profiles and analyzer versions are captured per snapshot; reports and human reviews enrich current reads without rewriting the original analysis.",
  ),
  topic(
    "application-security",
    "Application Security",
    "ProjectTrace finds supported static security patterns and highlights uncertain code for a person to review.",
    "A security conclusion needs evidence and a clear boundary on what was checked.",
    "Modeled Python inputs, assignments, local helpers and sinks; narrow JS/TS/Java hotspots.",
    "Confirmed modeled static flows or context-dependent security hotspots, with rule, source and remediation.",
    "Request input reaches a string-built SQL query through a modeled local flow.",
    ["secrets", "findings", "confidence"],
    "Inspect the flow and sanitizers; confirm or dismiss it with a documented reason.",
    "Runtime exploitability, full cross-file taint and broad framework/type models are unverified.",
    "Bounded Python flow propagation models selected SQL, shell, HTML, deserialization, path and HTTP sinks. Static proof classification stays separate from runtime authority.",
  ),
  topic(
    "dependencies",
    "Dependencies",
    "See which packages were observed, which versions are known and which advisory checks actually ran.",
    "Unexamined dependencies should not look safe simply because no advisory is displayed.",
    "Supported npm lockfiles and Python manifest/lockfile subsets.",
    "Package inventory, versions, direct/transitive observations, license metadata and CycloneDX SBOM.",
    "A declaration without an exact version remains UNKNOWN_VERSION; an unchecked version remains NOT_CHECKED.",
    ["findings", "policies", "scope"],
    "Export an SBOM and run authorized advisory checks where exact versions and provider configuration permit.",
    "Inventory and advisory coverage are partial. License metadata is an observation, not legal advice.",
    "Optional bounded OSV transport sends ecosystem/package/version only. States include VULNERABLE, CHECKED_NO_KNOWN_ADVISORY, NOT_CHECKED, CHECK_FAILED and UNKNOWN_VERSION.",
  ),
  topic(
    "secrets",
    "Secrets",
    "Secret-shaped values are masked and reported with their context instead of being shown in full.",
    "A development example and a likely live credential need different review decisions.",
    "Supported credential patterns and surrounding source context.",
    "Masked findings classified as fixture, example, production-like or unknown.",
    "A deliberately synthetic benchmark token is labeled TEST_FIXTURE and still stays masked.",
    ["application-security", "reviews", "security-privacy"],
    "Verify context, rotate a real exposed credential and record the review without pasting its value.",
    "Detection cannot cover every secret format or prove a credential is valid. No active credential test is performed.",
    "Redaction applies to source, graph identity, evidence and analysis output. Raw secret values are not sent to AI or public-site content.",
  ),
  topic(
    "infrastructure",
    "Infrastructure",
    "ProjectTrace reads supported deployment configuration to identify risky declarations.",
    "Configuration can reveal exposure before anything is deployed.",
    "Terraform HCL, supported Kubernetes/CloudFormation/Compose YAML and Dockerfiles.",
    "Static assets, identity/exposure observations and source-backed native findings.",
    "A privileged container or public storage declaration links to the exact configuration.",
    ["cloud-security", "evidence-graph", "findings"],
    "Check environment and intended scope, then review the source-backed recommendation.",
    "Templates and provider semantics are partial. A declaration is not proof of current deployment.",
    "HCL2 and safe YAML adapters parse data without evaluating IaC. Literal jsonencode policy objects are reparsed as HCL data; effective IAM semantics remain unproven.",
  ),
  topic(
    "cloud-security",
    "Cloud Security",
    "Static configuration evidence and live cloud observations have different authority and are shown separately.",
    "Teams should know whether a conclusion came from source or an observed cloud account.",
    "Supported IaC; a bounded read-only AWS inventory adapter when authorized credentials are configured.",
    "Assets, declared identities, exposure observations and actual-edge static risk paths.",
    "A production public-read bucket declaration conflicts with an explicit private-storage claim.",
    ["infrastructure", "evidence-graph", "claims"],
    "Use static evidence now; ask an administrator to configure an authorized read-only AWS account for live inventory.",
    "Live AWS validation is unverified in this installation. Azure/GCP live inventory, effective IAM and runtime paths are deferred.",
    "The AWS adapter allowlists STS/S3/EC2/IAM reads, checks account identity and repository authorization, and enforces time/item budgets. It never writes cloud resources.",
  ),
  topic(
    "findings",
    "Findings",
    "A finding is an observed issue or review signal. Its machine result and your review decision remain separate.",
    "One source-backed review queue prevents important issues from losing their engineering context.",
    "Native quality, security, secrets, dependencies, infrastructure and integrity observations.",
    "Severity, rule, location, snapshot, evidence, remediation, owner and review state.",
    "Marking a hotspot FALSE_POSITIVE records your judgment without rewriting the analyzer’s original evidence.",
    ["severity", "confidence", "reviews", "evidence"],
    "Filter by category and severity, inspect the evidence, and record a reason for your decision.",
    "Some categories are contextual hotspots. General-population precision and recall have not been established.",
    "Versioned rules and stable fingerprints distinguish new, existing and analyzer-baseline findings. Authorization scopes all investigation records.",
  ),
  topic(
    "evidence",
    "Evidence",
    "Evidence is the source information that supports or contradicts a conclusion.",
    "You should be able to check the proof instead of accepting an unexplained result.",
    "Source ranges, configuration, manifests, docs and supported observed cloud metadata.",
    "Provenance, authority, timestamps, hashes and snapshot scope.",
    "The session middleware at auth/session.py conflicts with the README’s JWT statement.",
    ["claims", "evidence-graph", "scope"],
    "Open the source range and check whether its authority is suitable for the claim.",
    "An import can suggest a technology without proving it is used in production.",
    "Authority is claim-specific: implementation/configuration and runtime observations have different roles. Exact source artifacts and graph edges remain traceable.",
  ),
  topic(
    "evidence-graph",
    "Evidence Graph",
    "The graph connects a selected claim or finding to its proof and related engineering objects.",
    "Connections explain which conclusions might be affected when evidence changes.",
    "Authorized nodes and evidence-backed typed relationships.",
    "A focused neighborhood of source, claims, findings and declared resources.",
    "Claim → README → session implementation → review and affected documentation.",
    ["evidence", "impact", "claims"],
    "Start from one selected object and expand a relevant relationship.",
    "Missing links stay missing. Source names alone do not establish deployment or runtime reachability.",
    "Relational nodes/edges are stored with tenant and snapshot scope. Retrieval traverses bounded authorized neighborhoods rather than an uncontrolled whole-system graph.",
  ),
  topic(
    "claims",
    "Claim Ledger",
    "The ledger keeps atomic technical statements and checks whether current evidence still supports them.",
    "Teams need to know when an important assumption no longer matches implementation.",
    "Supported documentation statements and deterministic implementation observations.",
    "Versioned claims, verification reasons, evidence links, history, ownership and review.",
    "‘FastAPI, PostgreSQL and JWT’ becomes three statements that can have different verification results.",
    ["statuses", "evidence", "drift"],
    "Inspect the supporting and contradicting evidence before deciding what to update.",
    "General compliance, runtime and unsupported security assertions cannot be verified from static source alone.",
    "Deterministic claim extraction/decomposition uses scoped evidence hierarchies. Status, severity, confidence and human review are distinct fields.",
  ),
  topic(
    "drift",
    "Drift",
    "Drift means a change left a previously supported statement out of date.",
    "Old documentation can cause teams to make decisions from an assumption that stopped being true.",
    "Earlier and current snapshots, changed evidence and claim history.",
    "Before/after status, changed files and affected statements/documents.",
    "Old code used JWT. New code uses sessions. Unchanged docs now conflict: VERIFIED → STALE → CONTRADICTED.",
    ["claims", "impact", "pull-requests"],
    "Compare the two snapshots and update the affected documentation or implementation.",
    "A first-snapshot contradiction is a consistency problem, not historical drift.",
    "Stable claim identities connect versions. Reverse graph impact and evidence hashes select claims for reverification while preserving historical records.",
  ),
  topic(
    "impact",
    "Impact",
    "Impact explains what else might need review because a source file changed.",
    "A small change can invalidate assumptions outside the edited file.",
    "Changed/deleted files and evidence-backed reverse graph relationships.",
    "Affected claims, docs, APIs, architecture, findings and policy links where modeled.",
    "Changing authentication middleware triggers review of a JWT claim and its documentation.",
    ["drift", "evidence-graph", "pull-requests"],
    "Review the linked objects, starting with high-severity conclusions.",
    "Impact is bounded by observed graph links; it is not a complete runtime dependency or call graph.",
    "Content hashes identify changed nodes. Bounded reverse traversal targets reverification and reports reused versus reverified declared claims.",
  ),
  topic(
    "architecture",
    "Architecture",
    "Compare supported architecture statements with relationships observed in source.",
    "An outdated system description can mislead changes and incident response.",
    "Supported docs, imports and configuration relationships.",
    "Atomic architecture claims, evidence and consistency/drift results.",
    "Docs describe Kafka while the newer implementation publishes through Redis.",
    ["claims", "drift", "evidence-graph"],
    "Inspect actual implementation evidence and the relevant snapshot history.",
    "Imported packages do not prove deployed topology. Broad architecture semantics remain partial.",
    "Supported deterministic claim types use source/configuration authority; undocumented or ambiguous relationships remain unverified.",
  ),
  topic(
    "api-integrity",
    "API Integrity",
    "Compare supported documented API routes with the routes found in source.",
    "API documentation should describe what the analyzed implementation actually exposes.",
    "Supported route declarations and OpenAPI contracts.",
    "Source-backed route evidence and documented-route mismatches.",
    "A contract lists /users/export, but the analyzed source does not establish that route.",
    ["evidence", "claims", "pull-requests"],
    "Check framework coverage and update the contract or route as appropriate.",
    "Dynamic routing, complete schemas and runtime behavior are not fully modeled.",
    "Deterministic route/contract extraction normalizes supported methods and paths. Missing evidence is not universal proof that a route cannot exist.",
  ),
  topic(
    "pull-requests",
    "Pull Requests",
    "One ProjectTrace decision explains how a change affects engineering evidence and risk.",
    "Reviewers can follow quality, security and integrity concerns in the same investigation.",
    "Base/head snapshots, changed findings, affected claims, policies and exceptions.",
    "An advisory PASS, WARNING, REVIEW_REQUIRED or FAIL with reasons and evidence links.",
    "An authentication change contradicts a critical claim and requires review of outdated documentation.",
    ["policies", "reviews", "impact"],
    "Follow every gate reason to its current evidence and record a review.",
    "Live GitHub check publication and private-source end-to-end behavior are not verified here. A gate does not automatically merge or block a provider PR.",
    "Native profile gate scope can distinguish new from existing findings while retaining claim contradictions. Gates capture snapshot and policy context.",
  ),
  topic(
    "policies",
    "Policies",
    "Policies turn observed evidence into an explainable review requirement.",
    "Teams can apply consistent expectations without hiding why a change needs attention.",
    "Findings, claim statuses, native profiles and scoped review exceptions.",
    "PASS, WARNING, FAIL, NOT_APPLICABLE or REVIEW_REQUIRED and concrete reasons.",
    "A critical contradiction can require review even when a new-findings-only profile excludes older quality findings.",
    ["pull-requests", "reviews", "claims"],
    "Inspect policy reasons and have an owner review exceptions with an expiry date.",
    "Policies are advisory in this release. They do not prove compliance or enforce deployment controls.",
    "Policy evaluation uses authorized captured snapshots/profiles and human review records; expiry restores review requirements rather than silently suppressing evidence.",
  ),
  topic(
    "reviews",
    "Human Review",
    "People record what they checked, what they decided and why.",
    "Human decisions need accountability without replacing the underlying machine evidence.",
    "Finding/claim evidence, role authorization, reasons and version numbers.",
    "Review decisions, owners, scoped risk exceptions and audit events.",
    "Confirm a session-auth contradiction after inspecting middleware, or record a false-positive reason.",
    ["findings", "policies", "audit"],
    "Use a precise reason and scope. Keep accepted-risk exceptions time-limited.",
    "A recorded decision is human attestation, not new runtime proof. All assignment/invitation lifecycle features are not implemented.",
    "Server-side role/repository checks and optimistic concurrency protect writes. Risk exceptions preserve actor, reason, scope and expiry.",
  ),
  topic(
    "audit",
    "Audit Trail",
    "The audit trail records who changed or reviewed an engineering conclusion and when.",
    "Teams need a reliable history of decisions, especially when an exception or assumption changes.",
    "Authorized imports, reviews, profile edits, retries and governance actions.",
    "Append-oriented events with actor, time, action and object context.",
    "A profile severity change or claim confirmation creates an attributable event.",
    ["reviews", "policies", "scope"],
    "Filter the trail and compare an action with its evidence and snapshot.",
    "Cryptographically immutable archives and enterprise audit export are deferred.",
    "Application audit writes append records transactionally. Original user audit IDs are preserved through additive migrations and upgrades.",
  ),
  topic(
    "ask",
    "Ask Engineering",
    "Ask a scoped technical question and receive an answer with evidence and explicit limits.",
    "An answer should help you investigate, rather than sound convincing without proof.",
    "Authorized current claims, source metadata and stored graph neighborhoods.",
    "Answer, verification status, confidence, scope, evidence, related claims and limitations.",
    "‘How is authentication implemented?’ returns supported session evidence and the conflicting JWT claim.",
    ["evidence", "claims", "scope"],
    "Open the citations and narrow repository scope when results are ambiguous.",
    "Insufficient evidence remains explicit. No external LLM or semantic vector provider is configured.",
    "PostgreSQL full-text search, deterministic metadata ranking and bounded authorized graph traversal ground the structured response. This is not an unrestricted chatbot.",
  ),
  topic(
    "statuses",
    "Understanding Statuses",
    "A claim’s status tells you how the current evidence relates to the statement.",
    "Supported, suggested, unknown, outdated and conflicting are different situations.",
    "Scoped supporting and contradicting evidence.",
    "VERIFIED, INFERRED, UNVERIFIED, STALE or CONTRADICTED.",
    "An unchanged README can move from VERIFIED through STALE to CONTRADICTED after a source change.",
    ["claims", "confidence", "severity"],
    "Read the reason and source scope alongside the status.",
    "VERIFIED applies to the supported statement and evidence scope; it does not mean the whole system is secure.",
    "Status is neither severity, probability nor review state. Current verification and historical transitions remain separate.",
  ),
  topic(
    "severity",
    "Understanding Severity",
    "Severity describes the potential importance of an issue, not whether the evidence is certain.",
    "Prioritization should not confuse impact with proof.",
    "Native rule defaults, profile overrides and finding/claim context.",
    "CRITICAL, HIGH, MEDIUM, LOW or INFO where supported.",
    "A high-severity hotspot can still require contextual validation.",
    ["confidence", "findings", "policies"],
    "Combine severity with confidence, scope, ownership and actual evidence.",
    "Severity alone is not a probability, exploitability verdict or magic risk score.",
    "Owner/admin profiles can override supported rule severity. The effective versioned profile is captured in the analysis snapshot.",
  ),
  topic(
    "confidence",
    "Understanding Confidence",
    "Confidence expresses the strength of the supported observation, separately from its importance.",
    "An uncertain signal should lead to investigation instead of a false claim of vulnerability.",
    "Parser coverage, modeled evidence paths and rule classification.",
    "Explicit confidence and confirmed-static versus hotspot distinctions.",
    [
      "A modeled source-to-sink flow is stronger than finding a suspicious function name.",
    ].join(""),
    ["application-security", "statuses", "severity"],
    "Inspect whether the necessary source, propagation and sink were actually modeled.",
    "Confidence is not a measured exploit probability or a real-world accuracy guarantee.",
    "Static analysis authority, rule metadata and limitations travel with the normalized finding; runtime authority is not inferred.",
  ),
  topic(
    "scope",
    "Understanding Scope",
    "Scope tells you which organization, repository, version and evidence a conclusion applies to.",
    "A correct conclusion about one snapshot may be wrong for another system or deployment.",
    "Authorized repository, branch/commit metadata, snapshot and analyzer versions.",
    "Visible source context and access-filtered results.",
    "A local ZIP’s source snapshot is known even when its real SCM commit is not verified.",
    ["repositories", "evidence", "ask"],
    "Check repository and snapshot before sharing or acting on a conclusion.",
    "Environment and runtime links require their own evidence. Names alone do not establish production scope.",
    "Tenant and repository authorization apply across records, caches, graph retrieval and jobs. Historical snapshots keep their captured analyzer/profile context.",
  ),
  topic(
    "workflows",
    "Common Workflows",
    "Use a short investigation loop: select source, check coverage, inspect proof, act, then compare the next version.",
    "A repeatable workflow keeps results understandable and decisions traceable.",
    "Your authorized source, analysis results and review intent.",
    "An imported repository or updated snapshot and recorded review actions.",
    "Import a ZIP → inspect a claim → review a finding → upload a new snapshot → inspect drift and the gate.",
    ["repositories", "findings", "reviews", "drift"],
    "Use a real workspace for your own source. The Northstar demo is a separate synthetic story.",
    "Importing another version does not execute it. Cloud/provider actions require explicit authorized configuration.",
    "New repository and New snapshot are distinct operations. The UI preserves canonical deep links, auth boundaries and snapshot-scoped investigation.",
  ),
  topic(
    "glossary",
    "Glossary",
    "Technical words describe concrete parts of the investigation, not mysterious scores.",
    "Common vocabulary helps developers and leaders discuss the same evidence.",
    "The terms used throughout ProjectTrace.",
    "Plain meanings, with technical detail when useful.",
    "SAST reads code for supported security patterns; SCA examines dependency inventory/advisories; IaC is infrastructure configuration stored as code.",
    ["statuses", "scope", "evidence"],
    "Use the glossary below whenever a term is unfamiliar.",
    "A term appearing in the product does not imply complete industry-wide coverage.",
    "AST is a syntax tree; a sink consumes potentially unsafe data; a fingerprint tracks finding identity; an SBOM records observed software components; a policy gate is an explainable review decision.",
  ),
  topic(
    "security-privacy",
    "Security / Privacy Model",
    "Source is treated as untrusted data, access is checked, and secret-shaped values are redacted.",
    "Private engineering information needs controls that are described honestly.",
    "Authorized imports, sessions, raw queued inputs and external connection metadata.",
    "Scoped source/evidence, masked findings and attributable authorized actions.",
    "OSV receives package identity/version, not repository source. No external AI receives source in this release.",
    ["secrets", "scope", "limitations"],
    "Import only authorized source and review operator retention/backup practices before sensitive production use.",
    "Operator-managed source retention remains in place. Self-service deletion, enterprise OIDC and full OS parser sandboxing are deferred.",
    "Argon2 passwords, HttpOnly sessions, CSRF/origin/RBAC checks, bounded safe ZIP parsing and isolated grammar helpers protect local workflows. Queued raw inputs are encrypted/expiring; persistent redacted source/history remain in the database.",
  ),
  topic(
    "limitations",
    "Limitations",
    "ProjectTrace shows what was observed and what is still unknown.",
    "Transparent limits prevent teams from treating partial static analysis as complete security proof.",
    "Engine coverage, errors, adapter capabilities and validation evidence.",
    "PARTIAL, unsupported, unchecked, unverified and deferred capability states.",
    "A parser diagnostic can make analysis PARTIAL while other engines still produce valid evidence.",
    [
      "code-quality",
      "application-security",
      "cloud-security",
      "security-privacy",
    ],
    "Review the validation report and coverage before deciding whether the evidence meets your needs.",
    "Live AWS proof, Azure/GCP, complete CFG/taint, all ecosystems, vector AI, enterprise identity/deletion, sustained production capacity and Docker deployment validation remain incomplete.",
    "The native platform has bounded regression and real service validation; these measurements do not establish full feature parity, comprehensive penetration testing or production-host readiness.",
  ),
];

export const guideForPage: Record<string, string> = {
  Overview: "start",
  Systems: "product-map",
  Components: "product-map",
  Repositories: "repositories",
  "Pull Requests": "pull-requests",
  "Code Quality": "code-quality",
  Security: "application-security",
  Dependencies: "dependencies",
  Secrets: "secrets",
  Infrastructure: "infrastructure",
  Cloud: "cloud-security",
  "Cloud Assets": "cloud-security",
  "Cloud Identities": "cloud-security",
  Exposure: "cloud-security",
  "Risk Paths": "cloud-security",
  "Claim Ledger": "claims",
  Drift: "drift",
  Architecture: "architecture",
  "API Integrity": "api-integrity",
  Evidence: "evidence",
  "Evidence Graph": "evidence-graph",
  "Ask Engineering": "ask",
  Findings: "findings",
  Policies: "policies",
  Reviews: "reviews",
  "Audit Trail": "audit",
  Connections: "scope",
  Settings: "security-privacy",
};
export const glossary = {
  Claim: "An atomic technical statement about software.",
  Evidence: "The source information supporting or contradicting a conclusion.",
  Snapshot: "The specific source version that was analyzed.",
  Drift:
    "A change that left previously supported engineering information out of date.",
  Impact: "Related objects that may need review after evidence changes.",
  SAST: "Static application security testing: supported security analysis of source.",
  SCA: "Software composition analysis: dependency inventory and advisory checking.",
  IaC: "Infrastructure as code: configuration describing infrastructure.",
  AST: "Abstract syntax tree: structured representation of source syntax.",
  SBOM: "Software bill of materials: an inventory of observed components.",
  Hotspot: "Context-dependent code that needs a security review.",
  "Source / sink":
    "Where data enters and where it reaches a sensitive operation.",
  Fingerprint: "Stable identity for tracking an observation across analyses.",
  Scope: "The repository, snapshot and evidence boundaries of a conclusion.",
  Gate: "An explainable policy decision for an analyzed change.",
  Authority: "What kind of evidence can support a particular claim.",
  Exception: "A documented, scoped, expiring human decision to accept risk.",
};
export const mapStages = [
  ["Sources", "repositories"],
  ["Native analysis", "code-quality"],
  ["Evidence Graph", "evidence-graph"],
  ["Claim Ledger", "claims"],
  ["Drift · impact · risk", "impact"],
  ["PR decision", "pull-requests"],
  ["Human action", "reviews"],
  ["Audit trail", "audit"],
];
