apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: projecttrace
resources: [production.yaml]
configMapGenerator:
  - name: projecttrace-nginx
    files: [default.conf=nginx.conf]
generatorOptions: {disableNameSuffixHash: true}
